config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount Commontator::Engine => '/commontator'

  devise_for :users

  root 'statuses#index'

  resources :users, constraints: { id: /.*/ }

  resources :groups do
    member do
      post :join
      get :can_join
      get :members
    end
  end

  resources :notifications, only: [:index] do
    member do
      get :read
    end
    collection do
      get :pull_unread
    end
  end

  resources :goals, only: [:show, :create, :new]
  get "goals/:id/:date", action: :on, as: :on, controller: :goals

  resources :statuses, only: [:show, :create, :update, :destroy] do
    resources :likes, only: [:create]
    resource :like, only: [:destroy]
  end

  get "/search", to: "search#index"
end

app/controllers/statuses_controller.rb
#encoding=utf-8

class StatusesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_status, only: [:show, :update, :destroy]

  def index
    @statuses = universe.members_statuses.page(params[:page])
    @group = universe
    session[:last_used_character_id] = Character.in_group(current_user, universe).take.id
  end

  def show
  end

  def create
    @status = current_character.statuses.build(status_params)
    @status.group = current_character.group

    target_goal = Goal.find(params[:status_goal_id])
    @status.goal = target_goal
    @status.action_goal = target_goal.last_action_goal

    if @status.save
      if params[:next_action_goal].present?
        next_action_goal_description = params[:next_action_goal]
      else
        next_action_goal_description = @status.action_goal.description
      end

      next_action_goal = ActionGoal.new(
        description: next_action_goal_description,
        goal: target_goal,
        status: @status)
      if next_action_goal.save
        unless current_character.group.home?
          Notification.create!(
            user: current_user,
            recipient: 0,
            description: "'#{current_character.group.name}' 그룹에서 #{view_context.datestring @status.verified_at}의 실천 인증을 올렸습니다.",
            link: group_path(current_character.group),
            group: current_character.group,
            status: @status)

          view_context.notify_to_group(@status)
        end
        redirect_to goal_url(target_goal)
      else
        redirect_to goal_url(target_goal), notice: 'error: next action goal on new status'
      end
    else
      redirect_to goal_url(target_goal), notice: 'error: new status'
    end
  end

  def update
    if @status.update(status_params)
      respond_to do |format|
        format.js
      end
    else
      render :edit
    end
  end

  def destroy
    @status.destroy
    respond_to do |format|
      format.html { redirect_to goal_url(@status.goal) }
      format.json { head :no_content }
    end
  end

  private
    def set_status
      @status = Status.find(params[:id])
    end

    def status_params
      params.require(:status).permit(:description, :user_id, :photo, :verified_at, :next_daily_goal)
    end
end

app/helpers/statuses_helper.rb
module StatusesHelper
  def status_at(date, cha=current_character)
    Status.at(date, cha).last
  end

  def first_verified_at
    Status.where(character: current_character).order(:verified_at).first.verified_at
  end

  def last_verified_at
    Status.where(character: current_character).order(:verified_at).last.verified_at
  end

  def status_photo (status)
    if status.photo?
      image_tag status.photo.url(:large), class: "#{'mobile' if browser.mobile?}"
    else
      content_tag(:span)
    end
  end

  def date_class(goal, day)
    str = ""
    if day == 0
      str += "active first-load "
    end
    if goal.statuses.at(day.days.ago.to_date).present?
      str += "verified"
    end
    return str
  end
end

app/views/statuses/_description.html.slim
== auto_link(html_escape(status.description.strip()), html: {target: '_blank'}) do |text| truncate(text, length: 30) end

app/views/statuses/_edit_goal.html.slim
.list-group.edit-goal-card
  span.list-group-item.dropdown.group-select
    = render 'groups/select'

  span.list-group-item.goal-container.monthly class=old_goal?('season')
    h4.list-group-item-heading data-toggle='tooltip' data-placement='top' title=seasonstring_detail(last_monthly_goal.season) = seasonstring last_monthly_goal.season
    a.modify-goal-link data-toggle='tooltip' data-plcaement='top' title="시즌 목표 수정"
      span.glyphicon.glyphicon-pencil
    = form_tag monthly_goal_path(last_monthly_goal), method: 'patch', remote: true, class: 'modify-actions'
      .buttons
        button.btn-xs.btn-link.btn-confirm 확인
        button.btn-xs.btn-link.btn-cancel type='button' 취소
      = text_area_tag 'monthly_goal[description]', '', placeholder: '목표가 무엇인가요?', class: 'form-control goal-textarea', required: true
    span.goal-description.list-group-item-text.nl2br = last_monthly_goal.description

  span.list-group-item.goal-container.weekly class=old_goal?('week')
    h4.list-group-item-heading data-toggle='tooltip' data-placement='top' title=weekstring(last_weekly_goal.weeknum) = weekstring_short
    - if no_weekly_goal? current_character, last_weekly_goal.weeknum
      = link_to '이번 주 목표를 설정해 보세요!', '#'
    - else
      a.modify-goal-link data-toggle='tooltip' data-plcaement='top' title="주간 목표 수정"
        span.glyphicon.glyphicon-pencil
      = form_tag weekly_goal_path(last_weekly_goal), method: 'patch', remote: true, class: 'modify-actions'
        .buttons
          button.btn-xs.btn-link.btn-confirm 확인
          button.btn-xs.btn-link.btn-cancel type='button' 취소
        = text_area_tag 'weekly_goal[description]', '', placeholder: '목표가 무엇인가요?', class: 'form-control goal-textarea', required: true
      span.goal-description.list-group-item-text.nl2br = last_weekly_goal.description

  - unless no_daily_goal? current_character, last_daily_goal.goal_date
    span.list-group-item.goal-container.daily class=old_goal?('day')
      h4.list-group-item-heading #{datestring last_daily_goal.goal_date} #{weekdaystring last_daily_goal.goal_date}
      a.modify-goal-link data-toggle='tooltip' data-plcaement='top' title="일일 목표 수정"
        span.glyphicon.glyphicon-pencil
      = form_tag daily_goal_path(last_daily_goal), method: 'patch', remote: true, class: 'modify-actions'
        .buttons
          button.btn-xs.btn-link.btn-confirm 확인
          button.btn-xs.btn-link.btn-cancel type='button' 취소
        = text_area_tag 'daily_goal[description]', '', placeholder: '목표가 무엇인가요?', class: 'form-control goal-textarea', required: true
      span.goal-description.list-group-item-text.nl2br = last_daily_goal.description

app/views/statuses/_like.html.slim
= form_for([status, status.likes.build], remote: true) do |f|
  .form-actions
    = f.button '좋아요', class: 'btn btn-xs btn-link'

app/views/statuses/_like_icon.html.slim
- if current_user.likes?(status)
  = form_for(status, url: status_like_path(status),
           html: { class: 'status-like-icon', method: :delete }, remote: true) do |f|
    = f.button '', class: 'glyphicon glyphicon-heart color-havit'
- else
  = form_for([status, status.likes.build], remote: true, html: {class: 'status-like-icon'}) do |f|
    = f.button '', class: 'glyphicon glyphicon-heart'

app/views/statuses/_liker_names.html.slim
- if status.likers.count > 0
  span.liker-names
    - if current_user.likes?(status)
      span 회원님
      = ", " if status.likers.count > 1
    - status.likers_other_than(current_user).each do |liker|
        = link_to liker.name, user_path(liker)
        | 님
        = ", " unless liker == status.likers_other_than(current_user).last
    | 이 좋아합니다.

app/views/statuses/_load_or_new.slim
- if goal.statuses.at(date).present?
  - goal.statuses.at(date).each do |status|
    = content_for :card_author_photo, flush:true
      a href=user_path(status.character.user)
        .avatar-wrapper.status-avatar
          = image_tag avatar_url(status.character.user)

    = content_for :card_title, flush:true
      a.status-user-name href=user_path(status.character.user) = status.character.user.name
      span 님의 #{datestring status.verified_at} #{weekdaystring status.verified_at} #{status.goal.theme}:
      span.action-goal =< status.action_goal.description

    = content_for :card_metainfo, flush:true
      a.time href=status_path(status)
        = timeago_tag status.created_at, format: "%B %-d일 %A %p %-l:%M", title: (l status.created_at, format: "%Y년 %B %-d일 %A %p %-l:%M")
      span.badges

    = content_for :card_message, flush:true
      span.description.nl2br == render 'statuses/description', status: status

    = content_for :card_photo, flush:true
      = status_photo(status)
      - if status.next_action_goal.present?
        .next-goal
          = "#{status.character.user.name}님의 다음 목표는 "
          span.color-havit = status.next_action_goal.description
          ' 입니다.

    = render partial: 'layouts/card', locals: {status_id: status.id}
  .want-more-verification.text-right
    a.btn.btn-havit-white 추가 실천 인증하기

.new-status-input class=(goal.statuses.at(date).present? ? 'hidden' : '')
  = hidden_field_tag 'status_goal_id', goal.id
  .status-body
    .status-description
      - date_str = date.today? ? "오늘은" : weekdaystring(date)+"에"
      = text_area_tag 'status[description]', nil, placeholder: date_str + ' 어떤 실천을 하셨나요?', required: true, class: 'form-control', resize: false
    .input-group.next-daily-goal data-toggle='tooltip' data-plcaement='bottom' title='다음 실천 목표를 입력해주세요. 미입력시 가장 최근 목표가 등록됩니다.'
      span.input-group-addon.next-goal-date = "다음 실천 목표:"
      = text_field_tag 'next_action_goal',
      '',
      placeholder: "미입력시 '#{goal.last_action_goal.description}'#{korean_postposition(goal.last_action_goal.description, :이가)} 자동 등록됩니다.",
      class: 'form-control next-daily-goal-input',
      autocomplete: 'off'
  .photo-preview.hidden
    span.photo-remove-btn.glyphicon.glyphicon-remove data-toggle='tooltip' title='실천 인증 사진 삭제'

  .status-footer
    .status-photo
      .status-photo-wrapper
        a.status-photo-link
          .photo-upload-wrapper
            span.glyphicon.glyphicon-camera
            = file_field_tag 'status[photo]', accept: 'image/png,image/gif,image/jpeg', class: 'hidden-file-input'
          span.photo-upload-description 실천 인증 사진
    button.btn.btn-link.color-havit.submit-btn type='submit'
      span.glyphicon.glyphicon-ok
      ' 인증 완료!

app/views/statuses/_new.html.slim
= form_tag "/statuses", method: "post", multipart: true, class: "new-status-form goal-container daily"
  ul.status-dates
    - 6.downto(0).each do |day|
      li class=date_class(@goal, day) data-toggle='tooltip' title=datestring(day.days.ago) action-date=day.days.ago.to_date
        .circle
        .connect-line
        = day==0 ? '오늘' : weekdaystring(day.days.ago.to_date, 'short')
        .emphasize
  = hidden_field_tag 'status[verified_at]', Date.current, class: 'status-verified-at'

  / .status-goal.text-center
  /   .goal-date
  /     span = "#{last_daily_goal.goal_date.strftime("%-m월 %-d일")} #{weekdaystring last_daily_goal.goal_date}"
  /     a.modify-goal-link data-toggle='tooltip' data-plcaement='top' title="목표 수정하기"
  /       span.glyphicon.glyphicon-pencil
  /   .modify-actions
  /     .buttons
  /       button.btn-xs.btn-link.btn-confirm type='button' data-id=last_daily_goal.id 확인
  /       button.btn-xs.btn-link.btn-cancel type='button' 취소
  /     = text_area_tag 'daily_goal[description]', '', placeholder: '목표가 무엇인가요?', class: 'form-control goal-textarea'
  /   span.goal-description.nl2br = last_daily_goal.description.strip()
  .load-or-new
    = render partial: 'statuses/load_or_new', locals: { goal: @goal, date: Date.current }

app/views/statuses/_photo_modal.html.slim
.modal.fade.photo-modal tabindex='-1' role='dialog' aria-hidden='true'
  .modal-dialog
    .modal-content
      .modal-body
      .modal-close
        button.close type='button' data-dismiss='modal' aria-label='close'
          span aria-hidden='true' &times;

app/views/statuses/_status.html.slim
= content_for :card_photo_original, flush: true
  = status_photo(status)
  = link_to '원본 사진 보기', status.photo.url, target: "_blank", class: 'btn btn-default btn-xs show-original-button'

/ = content_for :card_group, flush:true
/   - unless status.group.home?
/     span.fa.fa-group
/     span.name = status.group.name
/   - else
/     span

= content_for :card_author_photo, flush:true
  a href=user_path(status.character.user)
    .avatar-wrapper.status-avatar
      = image_tag avatar_url(status.character.user)

= content_for :card_title, flush:true
  a.status-user-name href=user_path(status.character.user) = status.character.user.name
  span 님의 #{datestring status.verified_at} #{weekdaystring status.verified_at} #{status.goal.theme}:
  span.action-goal =< status.action_goal.description

= content_for :card_metainfo, flush:true
  a.time href=status_path(status)
    = timeago_tag status.created_at, format: "%B %-d일 %A %p %-l:%M", title: (l status.created_at, format: "%Y년 %B %-d일 %A %p %-l:%M")
  span.badges

= content_for :card_option, flush:true
  span.fa.fa-chevron-down data-toggle='tooltip' data-placement='top' title='준비중입니다.'

= content_for :card_message, flush:true
  span.description.nl2br == render 'statuses/description', status: status
  = form_tag status_path(status), method: 'patch', remote: true, class: 'modify-actions'
      .buttons
        button.btn-xs.btn-link.btn-confirm 확인
        button.btn-xs.btn-link.btn-cancel type='button' 취소
      = text_area_tag 'status[description]', status.description, placeholder: '어떤 실천을 하셨나요?', class: 'form-control status-textarea', required: true

= content_for :card_photo, flush:true
  = status_photo(status)
  - if status.next_action_goal.present?
    .next-goal
      = "#{status.character.user.name}님의 다음 목표는 "
      span.goal-description = status.next_action_goal.description
      ' 입니다.

= content_for :card_actions, flush:true
  .like-form
    == render 'statuses/like_icon', status: status
  - if status.character_id == current_character.id
    .other-actions
      a.modify-status-link data-toggle='tooltip' data-plcaement='top' title='실천 인증 수정'
        span.glyphicon.glyphicon-pencil
      a.delete-status-link data-toggle='tooltip' data-plcaement='top' title='실천 인증 삭제' href="/statuses/#{status.id}" data-method='delete'
        span.glyphicon.glyphicon-remove
  .likers class="#{'expand-right' unless status.character_id == current_character.id}"
    == render 'statuses/liker_names', status: status

= content_for :card_comments, flush:true
  = commontator_thread(status)

= render partial: 'layouts/card', locals: {status_id: status.id}

app/views/statuses/_unlike.html.slim
= form_for(status, url: status_like_path(status),
           html: { method: :delete }, remote: true) do |f|
  .form-actions
    = f.button '좋아요 취소', class: 'btn btn-xs btn-link'

app/views/statuses/index.html.slim
.container-left
  .timeline-side-nav
    = render partial: 'layouts/timeline/nav', locals: { selected_goal: 'none' }
.container-center
  = render @statuses
.container-right

= render 'statuses/photo_modal'

= paginate @statuses, window: 2

app/views/statuses/show.html.slim
- if current_user == @status.character.user
  .container-left
    .timeline-side-nav
      = render partial: 'layouts/timeline/nav', locals: { current_group: current_character.group, selected_goal: @status.goal }

.container-center
  = render @status

- if current_user == @status.character.user
  .container-right
    .goal-visualization[class=@status.goal.type.downcase]
      .title
        span.theme.color-havit => @status.goal.theme
        span 실천 통계
      = render partial: "visualization/#{@status.goal.type.downcase}/on_the_right", locals: { goal: @status.goal }

= render 'statuses/photo_modal'

app/views/statuses/update.js.erb
$('.card-container.editing .card-message > .description').html("<%= j render 'statuses/description', status: @status %>")
$('.card-container.editing').removeClass('editing')