config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount Commontator::Engine => '/commontator'

  devise_for :users

  root 'statuses#index'

  resources :users, constraints: { id: /.*/ }

  resources :groups do
    member do
      post :join
      get :can_join
      get :members
    end
  end

  resources :notifications, only: [:index] do
    member do
      get :read
    end
    collection do
      get :pull_unread
    end
  end

  resources :goals, only: [:show, :create, :new]
  get "goals/:id/:date", action: :on, as: :on, controller: :goals

  resources :statuses, only: [:show, :create, :update, :destroy] do
    resources :likes, only: [:create]
    resource :like, only: [:destroy]
  end

  get "/search", to: "search#index"
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  before_action :set_param
  before_action :authenticate_user!

  def index
    if @query.blank?
      groups = Group.all.reject { |g| g.home? }
      @index = true
    else
      groups = Group.search(
        @query,
        page: @page,
        order: { created_at: :desc },
        per_page: 20,
        fields: [
          { name: :word_middle },
          :description
          ],
        operator: 'or')
    end

    @groups_joined = []
    @groups_not_joined = []
    @groups_not_joined_count = 0

    groups.each do |g|
      if view_context.joined_group?(g)
        @groups_joined << g
      else
        @groups_not_joined << g
        @groups_not_joined_count += 1
      end
    end

    @groups_count = groups.count
  end

  private

  def set_param
    @query = params[:query]
    @page = params[:page]
  end
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/search/_form.html.slim
= form_tag search_path, method: "get", class: 'search-form input-group'
  .input-append data-toggle='tooltip' data-placement='bottom' title='입력하지 않은 채로 검색 아이콘을 누르면 전체 그룹 목록이 나옵니다.'
    = text_field_tag :query, params[:query], class: 'form-control search-input', placeholder: '그룹 찾기'
    span.input-group-btn.search-input-btn
      button.btn.btn-default type='submit'
        span.glyphicon.glyphicon-search

app/views/search/_searched_group.html.slim
.searched-group
  .left-area.col-md-8.col-sm-7.col-xs-7
    .privacy-info.pull-left
      - if group.password.blank?
        span.glyphicon.glyphicon-globe data-toggle='tooltip' data-plcaement='top' title='누구나 그룹에 가입할 수 있습니다.'
      - else
        span.glyphicon.glyphicon-lock data-toggle='tooltip' data-plcaement='top' title='가입 코드를 입력해야 그룹에 가입할 수 있습니다.'
    a.title-link href=group_path(group)
      .title = group.name
    .description
      - if group.description.present?
        = group.description
      - else
        ' 그룹 설명이 없습니다.
  .right-area.col-md-4.col-sm-5.col-xs-5
    .metainfo
      .admin-info.pull-left
        ' 관리자:
        =< link_to Character.admin(group).user.name, user_path(Character.admin(group).user)
      .members-info.pull-right
        span.current-members-count => group.characters.count
        ' /
        span.member-limit
          - if group.member_limit == 0
            span.infinite-members data-toggle='tooltip' data-plcaement='top' title='그룹 멤버 수의 제한이 없습니다.' &infin;
          - else
            =< group.member_limit
    .group-join-div class=group_status(group)
      .already-joined
        = button_tag '가입한 그룹입니다.', type: 'button', class: 'btn btn-success btn-block btn-lg disabled', disabled: true
      .full-group
        = button_tag '그룹이 가득찼습니다.', type: 'button', class: 'btn btn-success btn-block btn-lg disabled', disabled: true
        span.
      = form_tag join_group_path(group), method: 'post', class: "group-join-form"
        .group-passcode
          = text_field_tag 'group[password]', nil, placeholder: '가입 코드를 입력하세요.', class: 'form-control passcode-input'
        .group-join-btn
          = submit_tag '가입하기',
            data: { id: group.id },
            class: "btn btn-success btn-block #{'btn-lg' if group.password.blank?}"

app/views/search/index.html.slim
.search-result-container.container-center
  - if browser.mobile?
    == render partial: 'search/form'
  .search-results.show-all
    .search-result-description
      - if defined? @index
        | Havit에 있는 모든 그룹의 목록입니다. 원하는 그룹을 찾아 보세요!
      - else
        | '#{@query}'#{korean_postposition(@query, :으로)} 그룹 #{@groups_count}개가 검색되었습니다.
    .menus
      button.btn.btn-xs.btn-link[trigger='show-not-joined' class="#{'disabled' if @groups_not_joined_count == 0}"] 가입하지 않은 그룹만 보기 (#{@groups_not_joined_count})
      button.btn.btn-xs.btn-link.active[trigger='show-all'] 모두 보기 (#{@groups_count})
    .searched-groups
      .groups-not-joined
        - @groups_not_joined.each do |group|
          = render partial: 'search/searched_group', locals: { group: group }
      .groups-joined
        - @groups_joined.each do |group|
          = render partial: 'search/searched_group', locals: { group: group }