config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount Commontator::Engine => '/commontator'

  devise_for :users

  root 'statuses#index'

  resources :users, constraints: { id: /.*/ }

  resources :groups do
    member do
      post :join
      get :can_join
      get :members
    end
  end

  resources :notifications, only: [:index] do
    member do
      get :read
    end
    collection do
      get :pull_unread
    end
  end

  resources :goals, only: [:show, :create, :new]
  get "goals/:id/:date", action: :on, as: :on, controller: :goals

  resources :statuses, only: [:show, :create, :update, :destroy] do
    resources :likes, only: [:create]
    resource :like, only: [:destroy]
  end

  get "/search", to: "search#index"
end

app/models/group.rb
class Group < ActiveRecord::Base
  searchkick word_middle: [:name], text_middle: [:description]

  has_many :characters, dependent: :destroy
  has_many :members, through: :characters, source: :user
  has_many :goals
  has_many :members_statuses, class_name: "Status"

  validates :name, presence: true, length: { maximum: 50 }
  validates :description, length: { maximum: 200 }
  validates :password, length: { maximum: 20 }
  validates :member_limit, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :creator, presence: true

  def home?
    self.name == 'Universe'
  end
end

app/controllers/groups_controller.rb
#encoding=utf-8

class GroupsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_group, only: [:show, :edit, :update, :destroy, :can_join, :join, :members]

  def index
    redirect_to root_url unless current_user.email == 'evermentors@gmail.com'
    @groups = Group.all
  end

  def show
    if @group.home?
      if params.include?('status-id')
        redirect_to (root_url + '?status-id=' + params['status-id'])
      else
        redirect_to root_url
      end
    else
      character = Character.in_group(current_user, @group)
      if not character.blank?
        session[:last_used_character_id] = character.take.id
        @statuses = @group.members_statuses.page(params[:page])

        render 'statuses/index'
      elsif @group.password.blank?
        @statuses = @group.members_statuses.page(params[:page])
        render 'groups/not_joined', locals: { hidden: false }
      else
        render 'groups/not_joined', locals: { hidden: true }
      end

    end
  end

  def new
    @group = Group.new
    @submit_text = '그룹 만들기'
  end

  def edit
    redirect_to @group unless current_character.is_admin
    @submit_text = '그룹 정보 수정'
  end

  def join
    @group.characters.create user_id: current_user.id, order: (current_user.characters.count + 1), is_admin: false
    redirect_to @group, notice: "[#{@group.name}] 그룹에 가입했습니다."
  end

  def can_join
    @group_status = view_context.group_status(@group)
    if @group_status == 'need-passcode'
      if @group.password == params[:passcode]
        @passcode_status = 'right-passcode'
      else
        @passcode_status = 'wrong-passcode'
      end
    else
      @passcode_status = 'right-passcode'
    end
  end

  def members
    @members = @group.characters
  end

  def create
    @group = Group.new(group_params)
    @group.creator = current_user.id
    @group.member_limit = 0 if @group.member_limit.blank?

    if @group.save
      @group.characters.create user_id: current_user.id, order: (current_user.characters.count + 1), is_admin: true
      redirect_to @group, notice: "[#{@group.name}] 그룹을 만들었습니다."
    else
      render :new
    end
  end

  def update
    redirect_to @group unless current_character.is_admin
    if @group.update(group_params)
      redirect_to @group, notice: "[#{@group.name}] 그룹의 정보를 변경했습니다."
    else
      render :edit
    end
  end

  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_group
      if Group.find_by_id(params[:id]).nil?
        render text: '그룹이 존재하지 않음'
      else
        @group = Group.find(params[:id])
      end
    end

    def group_params
      params.require(:group).permit(:name, :description, :password, :member_limit)
    end
end

app/helpers/groups_helper.rb
#encoding=utf-8

module GroupsHelper
  def is_full? (group)
    group.member_limit > 0 and group.characters.count >= group.member_limit
  end

  def joined_group? (group, user=current_user)
    not Character.in_group(user, group).blank?
  end

  def group_status (group)
    if joined_group?(group)
      'already-joined'
    elsif is_full?(group)
      'full-group'
    elsif group.password.present?
      'need-passcode'
    end
  end

  def notify_to_group (status, group=current_character.group)
    if not Rails.env.test?
      client ||= SendGrid::Client.new do |c|
        c.api_user = ENV['SENDGRID_USERNAME']
        c.api_key = ENV['SENDGRID_PASSWORD']
      end

      addresses = []
      group.characters.each do |cha|
        addresses << cha.user.email unless cha == current_character
      end

      addresses.each do |address|
        goal_str = "<strong>#{datestring status.verified_at} #{weekdaystring status.verified_at}의 실천 목표:</strong> <span style='color: #40BD9C; font-weight: normal;'>#{status.action_goal.description}</span>"
        mail = SendGrid::Mail.new do |m|
          m.to = address
          m.from = 'evermentors@gmail.com'
          m.subject = "[Havit] #{current_user.name}님이 '#{group.name}' 그룹에서 #{status.goal.theme} 실천을 하셨습니다."
          m.html ="
          <p style='position:relative; margin-top:0;'>
            <div style='display: inline-block; max-height: 31px; height: 31px; width: 31px; max-width: 31px; overflow: hidden;'>
              <img src='#{avatar_url(current_user)}' style='width: 31px; height: 31px;'>
            </div>
            <span style='display: inline-block; vertical-align: top; line-height: 31px; margin-top: 0; margin-left: 3px; padding-top: 0;'>#{current_user.name}</span>
          </p>
          <p style='margin:0; font-size:15px;'>#{goal_str}</p>
          <hr style='width: 30px; display: inline-block;'>
          <p style='white-space: pre-wrap; margin:0;'>#{auto_link(html_escape(status.description), html: {target: '_blank'}) do |text| truncate(text, length: 30) end}</p>
          <hr style='width: 30px; display: inline-block;'>
          <p style='font-size: small; margin-top:0;'>
            <a href=#{group_url(group) + '?status-id='+status.id.to_s}>Havit에서 보기</a>
          </p>"
        end
        client.send(mail)
      end
    end
  end
end

app/views/groups/_form.html.slim
= simple_form_for(@group, html: {autocomplete: 'off'}) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name, label: '그룹 이름', placeholder: '그룹의 특징을 잘 나타내보세요.', input_html: { maxlength: 50 }, as: :string
    = f.input :description, label: '그룹 설명', placeholder: '멤버에게 그룹을 소개하고 그룹의 목적에 대해 알려주세요.', input_html: { maxlength: 200 }
    = f.input :password, label: '그룹 입장 코드', placeholder: '비워놓으면 누구나 가입할 수 있는 공개 그룹이 됩니다.', input_html: { maxlength: 20 }, as: :string
    = f.input :member_limit, label: '그룹 멤버 수 제한', hint: '0으로 설정하면 제한이 없어집니다.'

  .form-actions
    = f.button :submit, @submit_text

app/views/groups/_group.html.slim
.header.bg-success
  .metainfo
    .group-privacy-info
      - if @group.password.blank?
        span data-toggle='tooltip' data-plcaement='top' title='누구나 그룹에 가입할 수 있습니다.'
          span.glyphicon.glyphicon-globe
          span.privacy-description 공개 그룹
      - else
        span data-toggle='tooltip' data-plcaement='top' title='가입 코드를 입력해야 그룹에 가입할 수 있습니다.'
          span.glyphicon.glyphicon-lock
          span.privacy-description 비공개 그룹
    .group-members-info
      span.glyphicon.glyphicon-user
      .members
        => link_to @group.characters.count, members_group_path, class: 'current-members-count'
        ' /
        span.member-limit
          - if @group.member_limit == 0
            span.infinite-members data-toggle='tooltip' data-plcaement='top' title='그룹 멤버 수의 제한이 없습니다.' &infin;
          - else
            =< @group.member_limit

  .title title=@group.name = @group.name
  .management.group-join-div class=group_status(@group)
    - if current_character.group == @group
      - if current_character.is_admin
        a href=edit_group_path data-toggle='tooltip' data-plcaement='top' title='그룹 설정 변경'
          span.glyphicon.glyphicon-cog
    - elsif @group.password.blank?
      a.btn.btn-sm.btn-success.join-group-link href=join_group_path(@group) data-method='post'
        span.glyphicon.glyphicon-plus
        span 그룹 가입
    - else
      = form_tag join_group_path(group), method: 'post', class: "join-group-form form-inline"
        .input-group.input-group-sm
          = text_field_tag 'group[password]', nil, placeholder: '가입 코드', class: 'form-control passcode-input'
          span.input-group-btn.group-join-btn
            = submit_tag '가입',
              data: { id: group.id },
              class: 'btn btn-success'

.body
  .description
    - if @group.description.present?
      = @group.description
    - else
      ' 그룹 설명이 없습니다.

app/views/groups/_select.html.slim
.dropdown-toggle id="dropdownMenu1" data-toggle="dropdown" aria-expanded="true"
  span.fa.fa-group.group-icon
  .group-title = current_character.group.home? ? "내 타임라인" : "#{current_character.group.name}"
  span.caret
ul.dropdown-menu role="menu" aria-labelledby="dropdownMenu1"
  - for group in current_user.explicitly_joined_groups
    - active = (group == current_character.group ? 'active' : '')
    li role="presentation" class=active
      a.menuitem role="menuitem" href=group_path(group) title="그룹 이름: #{group.name}"
        span.glyphicon.glyphicon-ok
        .group-name = group.name
        .group-description = group.description
  li role="presentation" class='create-new-group'
    a.menuitem role="menuitem" href=new_group_path
      span.glyphicon.glyphicon-plus
      span.description 새 그룹 만들기

app/views/groups/can_join.js.erb
target = $(".group-join-btn > input[data-id=<%= @group.id %>]").closest('.group-join-div')
<% if @group_status == 'full-group' %>
  target.addClass("<%= @group_status %>")
  target.parent().find('.current-members-count').text("<%= @group.characters.count %>")
  target.parent().find('.member-limit').text("<%= @group.member_limit %>")
<% else %>
  input = target.find('.passcode-input')
  input.attr('class', "form-control passcode-input <%= @passcode_status %>")
  <% if @passcode_status == 'wrong-passcode' %>
    if (input.parent().hasClass('group-passcode'))
      input.attr('placeholder', '잘못된 가입 코드입니다.').focus()
    else if (input.parent().hasClass('input-group'))
      input.focus()
      input.tooltip({container: 'body', title: '잘못된 가입 코드입니다.'})
      input.tooltip('show')
  <% end %>
<% end %>

app/views/groups/edit.html.slim
h1 그룹 관리하기

== render 'form'

= link_to 'Show', @group
'|
= link_to 'Back', groups_path

app/views/groups/index.html.slim
h1 Listing groups

table
  thead
    tr
      th Name
      th Description
      th Password
      th Member limit
      th
      th
      th

  tbody
    - @groups.each do |group|
      tr
        td = group.name
        td = group.description
        td = group.password
        td = group.member_limit
        td = link_to 'Show', group
        td = link_to 'Edit', edit_group_path(group)
        td = link_to 'Destroy', group, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Group', new_group_path

app/views/groups/members.html.slim
.container.group-members
  h3.text-center = "[#{@group.name}] 그룹"
  - @members.each do |member|
    .user-information
      .avatar-wrapper
        = image_tag avatar_url(member.user)
      h4.user-name
        = "#{member.user.name}"
        = "(관리자)" if member.is_admin

app/views/groups/new.html.slim
h1 새 그룹 만들기

== render 'form'

= link_to 'Back', groups_path

app/views/groups/not_joined.html.slim
= paginate @statuses, window: 2 unless hidden

- if no_monthly_goal?
  / TODO: recover after retrospect is complete
  / - if Status.where(character: current_character).blank?
  .no-monthly-goal
    = render 'goals/form'
  / - else
    / = render text: '월간회고 해라'
- else
  .container-header
    .edit-goal.container-sidebar
      = render 'statuses/edit_goal'
    .group-info-container.container-center
      = render @group

.container-body
  = render @statuses unless hidden

= paginate @statuses, window: 2 unless hidden

app/views/groups/show.html.slim
p#notice = notice

p
  strong Name:
  = @group.name
p
  strong Description:
  = @group.description
p
  strong Password:
  = @group.password
p
  strong Member limit:
  = @group.member_limit

= link_to 'Edit', edit_group_path(@group)
'|
= link_to 'Back', groups_path